### ISSUE TITLE
More explanation required

### ISSUE THREAD

**Issue by brendanpatterson** [roikles/Wordpress-Bem-Menu#16]
Hi, new to WP so struggling a little with getting this working - would it be possible to give some more detailed installation/implementation instructions? Currently getting 'You need to first define a menu in WP-admin' and unsure how to resolve. 

Thanks!

**Comment by roryashfordbentley** [comment]
Hi Brandon, I'll try my best to guide you through the process as best I can.

I'll try and walk you through each step in the setup and if you have any further issues or questions we can work it out together ;)

The first thing you need to do is _register_ a nav menu for use in wp-admin. This is done with the WordPress function `register_nav_menus()` which is documented here: https://codex.wordpress.org/Function_Reference/register_nav_menus

The way that _I_ use it is as part of a function I run in my `functions.php` file. If you don't have a function.php file in your theme folder you can create one and it will be executed by WordPress automatically.

My usual setup is something like this:

```php
add_action( 'after_setup_theme', 'register_my_menu' );

function register_my_menu() {
  register_nav_menus(array(
        'main_menu' => 'main menu'
    ));
}
```
`register_nav_menus()` accepts an array as an argument which makes it really simple to add subsequent menus if you need to. The first value is essentially the slug we use to identify the menu within our _code_ and the second value is the description of the menu that appears in _wp-admin_

Now that we have registered a menu we can log in to the WordPress backend and navigate to Menus in the Appearance menu.

If you already have a menu setup you need to make sure that it has a `Menu Name`. For the benefits of this tutorial lets say that you have called the menu `My Menu` and click `Save Menu`

Next we need to click on the `Manage Locations` tab. If we did everything correctly in our functions.php file there should be a single location called `main menu` underneath `Theme Location`. If you click the dropdown menu underneath `Assigned Menu` you should be able to select `My Menu`. finally hit Save and return to the `Edit Menus tab`.

Right at the bottom you should see a checkbox next to `Theme Locations`. If everything is setup correctly it should say `main menu` next to the checkbox. Make sure its ticked and everything should be done on the backend.

With everything above completed and working you should now be able to run 

```
<?php bem_menu('main_menu','main-menu'); ?>
```

Main menu is the first parameter we defined in `register_nav_menus()` and the second argument `main-menu` is the prefix of all the classes we will output. you can change the second argument to whatever suits your naming convention.

I hope this helps you get WordPress BEM Menus working and if you have any other issues just update this ticket, or add a new one.

-Rory

**Comment by brendanpatterson** [comment]
Awesome thanks! 👍

**Comment by roryashfordbentley** [comment]
Glad it helped!
