### ISSUE TITLE
How to add serial numbers to menu items

### ISSUE THREAD

**Issue by afider** [roikles/Wordpress-Bem-Menu#2]
Hi!
How can I add serial numbers to first level menu items as modifiers:  
`.main-nav__item_order_1`, `.main-nav__item_order_2`, and so on..?

**Comment by roikles** [comment]
By default bem_menu uses the menu order as it appears in wp-admin.

For custom functionality like this you would need to customise the Walker yourself as Wordpress Bem Menu doesn't have this functionality.

https://codex.wordpress.org/Class_Reference/Walker
