### ISSUE TITLE
Notice: Undefined index: thumbnail, medium, large

### ISSUE THREAD

**Issue by yumyo** [roikles/Wordpress-Bem-Menu#6]
All of the above referred by dummy-uploader.php line 127, 128

**Comment by roikles** [comment]
Hi @yumyo I'm not sure I understand what you are reporting here? Can you elaborate a bit?

**Comment by yumyo** [comment]
I'm just getting these errors in any admin screen.

**Comment by roikles** [comment]
How does this relate to Wordpress Bem Menu exactly?

**Comment by yumyo** [comment]
roikles I can't belive I've posted in wrong window : ( Apologize. And thank you for fast reply.

**Comment by roikles** [comment]
Any time :)
