### ISSUE TITLE
Custom Link-Classes in menus are not in plugin's output

### ISSUE THREAD

**Issue by Volker-E** [roikles/Wordpress-Bem-Menu#8]
Custom CSS classes in menus are not in plugin's output. That seems like a useful missing addition.

**Comment by roikles** [comment]
This is something I have definitely overlooked. I'll work on an update, should be fairly simple to add in.

**Comment by roikles** [comment]
I have created a pull request #9 that you can drop in to a project to test.

**Comment by Volker-E** [comment]
Thanks!
